### ISSUE TITLE
Get Topic Method

### ISSUE THREAD

**Issue by Nozemi** [Nozemi/ForumLib#1]
Currently the way the Topic::getTopic() method is handled, makes it bad. Because if there are two topics with very similar name, it'll match both of them upon searching with a string (which I made the site do). Usually there are no topics with similar names under the same category, so making the method filter by the name and the category ID the topic is supposed to be under will be a sufficient solution.

**Comment by glombers** [comment]
It's a tough problem to solve. At amiss here you have to have users and subjects alike. Or exclude it completely I ate flarum

**Comment by Nozemi** [comment]
It's easy to solve, I'm just too lazy to fix it right now. Will be a simple fix anyway. :)

**Comment by Nozemi** [comment]
This is now resolved as of commit: a8a4b2323fc861b164562cd5d7904cc72e3b5c5d.

**Comment by glombers** [comment]
I am impressed with your skills You have a desire to make the engine forum? I can take care of this style is good xD
